sudo: required
dist: precise
language: php
services:
  - docker
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
before_script:
  - phpenv config-rm xdebug.ini
matrix:
  include:
  - php: "7.2"
  - php: "7.1"
  - php: "7.0"
  - php: "5.6"
  - php: "5.5"
  - php: "5.3"
script:
  - docker-compose up -d
  - composer install
  - vendor/bin/phpunit
