version: "3.7"
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    networks:
      - public
  php:
    container_name: php
    image: splitbrain/phpfarm
    volumes:
      - .:/var/www
    networks:
      - public
networks:
    public:
