version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: composer update
      - run: docker run -d --name phpfarm splitbrain/phpfarm
      - run: docker cp ./ phpfarm:/var/www
      - run: docker exec phpfarm php-5.6 vendor/bin/phpunit
