version: 2
jobs:
  build:
    docker:
      - image: splitbrain/phpfarm
    working_directory: ~/repo
    steps:
      - checkout
      - run: curl -s https://gist.githubusercontent.com/frgomes/a6f889583860f5b330c06c8b46fa0f42/raw/ea73323e97ae8b9d5c6e27dbd6c00811cdf49bbc/install-docker.sh
      - run: install-docker.sh
      - run: curl -s https://getcomposer.org/installer | php-5.6 && mv composer.phar /usr/local/bin/composer
      - run: php-5.3 /usr/local/bin/composer install
      - run: php-5.3 vendor/bin/phpunit
      - run: php-5.4 /usr/local/bin/composer install
      - run: php-5.4 vendor/bin/phpunit
      - run: php-5.5 /usr/local/bin/composer install
      - run: php-5.5 vendor/bin/phpunit
      - run: php-5.6 /usr/local/bin/composer install
      - run: php-5.6 vendor/bin/phpunit
      - run: php-7.0 /usr/local/bin/composer install
      - run: php-7.0 vendor/bin/phpunit
      - run: php-7.1 /usr/local/bin/composer install
      - run: php-7.1 vendor/bin/phpunit
      - run: php-7.2 /usr/local/bin/composer install
      - run: php-7.2 vendor/bin/phpunit
